### ISSUE TITLE
Cursor to go all the way up / down a long thread ?

### ISSUE THREAD

**Issue by gbdomubpkm** [timsueberkrueb/webber#12]
Is it possible to activate an option to go quickly to the bottom of a long thread ? 
(usable on a ubports forum webapp for example).  Because currently, it is necessary to do a very long scrolling with the finger from bottom to top manually.

**Comment by timsueberkrueb** [comment]
Can you elaborate a bit, please (e.g. screenshot)? I'm not sure I understand.

**Comment by gbdomubpkm** [comment]
Make a webapp with ubports forum.
Open https://forums.ubports.com/topic/1893/osk-enhancements-proposals/ and try to go directly to the bottom of the thread... 😉
Is that clearer?

**Comment by timsueberkrueb** [comment]
Yep, I understand, thanks.

First of all: This is not something that can be implemented in Webber. Webber just generates a click package using the standard `webapp-container` from Morph (https://github.com/ubports/morph-browser), so this would be a feature request for the `webapp-container` rather than Webber itself.

It's certainly possible to implement this for a reasonable subset of websites, however it might not be doable for all possible websites because this depends on how a particular website is implemented. For example, Discourse (the software that powers the UbPorts forums), dynamically loads new page content as you scroll down (so the height isn't initially known to the webview), while other pages might require you to interact in a specific way (e.g. press a button) to get to the "real" end of the page.

However, Discourse (and hopefully other websites) recognize the `End` key to scroll to the very end of the site. One could trigger that manually to achieve scrolling to the very end (e.g. `QKeySequence::MoveToEndOfDocument`). This would work for websites with a static height or websites with a "dynamic" height that recognize the `End` key (like Discourse). Maybe this could be added to the context menu. I think that's a reasonable feature to add and I would recommend you to propose this as an addition to Morph's `webapp-container` :+1:

**Comment by timsueberkrueb** [comment]
In the case of Discourse there's also a button in the web page to do this (double arrow down at the bottom right of the screen).

**Comment by gbdomubpkm** [comment]
A question as a neophyte as I am: while browsing the ubports doc, I saw this command line: '-- enable-adressbar' . Could this be useful for you? (or is it already in use for something).

**Comment by timsueberkrueb** [comment]
Yep, that enables the title bar (represented using a radio button under "Customize" in Webber) :)

**Comment by gbdomubpkm** [comment]
Feature request done.
