### ISSUE TITLE
Opening links in private windows

### ISSUE THREAD

**Issue by gbdomubpkm** [timsueberkrueb/webber#13]
Can you make sure that links that are not confined in a webapp (i.e. when they are not defined in patterns) open in private windows and not in classic windows. This would be a minimal protection to avoid the recording of cookies i think.

**Comment by timsueberkrueb** [comment]
This is a feature request for `webapp-container` I think. If `webapp-container` supports this feature, Webber can support it as well.

**Comment by gbdomubpkm** [comment]
Ok. Do you know the link to eventually do this?

**Comment by timsueberkrueb** [comment]
Since `webapp-container` is a part of Morph, this is the place to go: https://github.com/ubports/morph-browser. I could imagine something like a setting in Morph that opens links in private windows by default rather than in regular windows. Maybe this option exists already? Should check before opening an issue there.

**Comment by gbdomubpkm** [comment]
Indeed. Since it depends directly on morph-browser, there was already an open feature request https://github.com/ubports/morph-browser/issues/145. And considering, I think the interest of this, I'm going to  "relaunch the case".

**Comment by gbdomubpkm** [comment]
Feature now implemented on dev channel.
