### ISSUE TITLE
Lack of Strips with various options of a website

### ISSUE THREAD

**Issue by gbdomubpkm** [timsueberkrueb/webber#27]
In some webapps, unlike web pages of some websites, there is not the strip that contains various options.
See here for the Equipe site, but this is also the case for banking or telecommunication sites ...

![WEBEQUIPE20200407](https://user-images.githubusercontent.com/50362604/78648452-48df4d00-78bc-11ea-9d87-8481021f9f84.png)
website

![WEBAPPEQUIPE20200407](https://user-images.githubusercontent.com/50362604/78648586-74face00-78bc-11ea-8916-6c3f736a96e9.png)
webapp without the strip

In your opinion, is there a particular request possible to make in Morph concerning the webapp-container ? As it doen't concern webber app directly i think..
Thank you in advance for your advice.

**Comment by timsueberkrueb** [comment]
This only happens for me with L'Équipe if I enable the option to show a title bar in Webber.
This behavior is controlled by `webapp-container` and apparently occurs when the `--enable-addressbar` flag is set.

I'm pretty sure that this is a bug in `webapp-container`. I have the suspicion that there is a QML layouting issue in `webapp-container` because it looks part of the menu at the bottom is shown, which could indicate that the webview's height actually goes beyond the visible area.
This theory is supported by other examples where only part of the footer and the vertical scrollbar is visible if one scrolls to the very bottom of a page.

 I think we should open an issue at [ubports/morph-browser](https://github.com/ubports/morph-browser).

**Comment by gbdomubpkm** [comment]
You're absolutely right. 
For 'L'Équipe', creating a webapp using the 'Show title bar with previous/next buttons' option and then zooming the webapp to 200% will bring up the options strip.
The 'Don't show title bar' option, if it's enough to make this option strip appear for the l'Équipe webapp, is not enough to make this strip appear for a webapp created with my bank, but the problem is most certainly identified.

**Comment by gbdomubpkm** [comment]
Done new issue opened for morph-browser

**Comment by gbdomubpkm** [comment]
Fixed.
By this https://github.com/timsueberkrueb/webber/issues/20 as been fixed too! Good for the webapps !
