### ISSUE TITLE
Publish Webapp to OpenStore

### ISSUE THREAD

**Issue by 2br-2b** [timsueberkrueb/webber#36]
What if there was a way built into Webber to publish a webapp to the OpenStore after creation? That would give a big boost to the apps available in the market, and it'd be much simpler than learning to use Clickable to make a web app (which I can't find a good tutorial for).

This requires that:
1. click packages are not only compatible with the phone they were made on (which I don't think they are, but they may be)
2. A way to interface with the OpenStore and submit the app
3. I'm not sure what else is needed
4. Maybe a way to make git repo with the code? This would be much more complicated, and would probably be added in later.

**Comment by timsueberkrueb** [comment]
Hey, Webber was intentionally designed to *discourage* this.
There are some great webapps (e.g. for YouTube) in the Open Store which are not only shortcuts but enhance the website with additional features. Those webapps are great and should be uploaded in the store.

However, many webapps in the store, and also all webapps created by Webber, are simply shortcuts. They don't provide any additional value besides being a quicker way to access the site.

Putting this kind of webapp in the store is problematic for several reasons:

* Security issues: e.g. webapps wrapping banking apps should at least require a review before each update
* Trademark issues: most webapps are unofficial
* Lack of maintenance: many webapps are not being maintained/updated
* Lack of benefit: Most are simply shortcuts and don't provide any additional value
* Store pollution: Native apps are harder to find because the store is filled with webapps

Therefore, Webber was created to make creating shortcuts so simple that there is no need to put shortcut webapps into the store anymore. Webber is only an interim solution, tough. Ideally, PWA support should be integrated in the system webbrowser and make Webber obsolete.
