### ISSUE TITLE
Creating webapp icons

### ISSUE THREAD

**Issue by gbdomubpkm** [timsueberkrueb/webber#5]
Shortcuts do not always have site icons.  Is that normal? 
Am I missing something to make them appear? For example with the website https://tenup.fft.fr/ or https://streema.com

**Comment by timsueberkrueb** [comment]
Yeah, that happens when the page has no app icon specified in its page meta-data. Webber [currently looks for](https://github.com/timsueberkrueb/webber/blob/master/src/core.rs#L52): 

*  `html > head > link[rel='icon']`
* `html > head > link[rel='apple-touch-icon']`

Potential features to handle this include:

* Allow the user to select a custom icon via Content Hub
* Screenshot the website

**Comment by gbdomubpkm** [comment]
Yes. And If you could, maybe having the choice to use either method in webber would be good.

In the meantime, I've been struggling to use github under morph-browser. It seems impossible now !!

**Comment by timsueberkrueb** [comment]
:+1: Yep, will do this eventually.
As for the GitHub thing: Will test later to understand what you mean.

**Comment by timsueberkrueb** [comment]
Enjoy!
As for the GitHub thing: yeah, looks like QtWebEngine/the underlying Chromium could use an update ...

**Comment by gbdomubpkm** [comment]
Thank you 👍👍

**Comment by timsueberkrueb** [comment]
You're very much welcome, please report any issues you stumble upon (if any)!

**Comment by gbdomubpkm** [comment]
Thank you again.
In a moment of calm, I will indeed have some observations to make go up more completely: but quickly said, the name automatically created in properties can be refused to create the .click (because of the special characters and its length) and when you navigate for the icon between default, screenshot, custom, the screenshot is lost (square becomes grey). The screeshot is also lost if you try to change the name in properties.
Good afternoon (if it's the right time!)
