### ISSUE TITLE
Youtube login issue

### ISSUE THREAD

**Issue by Ygrex** [timsueberkrueb/webber#61]
Youtube mentioned for a specific example, meantime the same observed on other sites as well.

So the regular scenario evolves as follows. Navigating WebUI for the necessary application in Morph Browser, after I ensure it has everything I need, I "share" it with Webber. I tap on the new app icon and it opens up a simplified browser window but not sharing cookies with Morph. And here it happens that with some applications I cannot login (= set cookies), for example it happens with Youtube.

How it looks like: I tap on "Log in", usually it is a web menu item. It case of Youtube: tap on top-right corner icon -> login. And the frustrating part is that it does not navigate to login page, it stays on the page it is, simply put - nothing happens.

To work it around I tried long tapping on "Log in" and "Open link in new window". I guess it would give expected results if it were "Open link in THIS window", but in reality it sends the link to Morph browser where I logged in already.

**Comment by timsueberkrueb** [comment]
Hi, the problem is that web apps are scoped to specific url patterns. That means that if you create a web app for YouTube, it will only work on urls of the format `https?://youtube.com/*`. When you try to login to YouTube, it redirects to a Google url. Therefore you can solve your problem by adding the url pattern `https?://*.google.com/*` under the customization options when creating the web app:

![screenshot20230720_123717352](https://github.com/timsueberkrueb/webber/assets/11774614/386e053a-0ebd-486d-9715-2ba75b0cf4af)
