### ISSUE TITLE
Integrating functions similar to this app directly into Morh Browser

### ISSUE THREAD

**Issue by JamiKettunen** [timsueberkrueb/webber#66]
I filed https://gitlab.com/ubports/development/core/morph-browser/-/issues/543 (`Ability to create webapp shortcuts directly`) two months back and I think it really would be awesome if Morph had built-in installable PWA support, and I was just wondering what are your thoughts on this? Were there technical limitations way back when this app was created that prevented stuff like this from being added to the browser itself or?

**Comment by timsueberkrueb** [comment]
Yes, I think integrating Webber's functionality into Morph would be great. Part of my motivation for this app was to try out the combination of using Rust with Qt for Ubuntu touch app development. It started as a simple prototype. As it turned out to be generally useful, I continued to develop it. There are no technical reasons why it couldn't be implemented in Morph itself. On the contrary, I would encourage anyone to do so :)
